<?php
require_once dirname(__DIR__) . '/shared/module_auth.php';
require_once dirname(__DIR__) . '/shared/csrf.php';
require_once 'finance_manager.php';
bootModule(['module' => 'finance', 'page' => 'budget', 'pageTitle' => 'Budget Planning - ARMIS', 'moduleName' => 'Finance', 'moduleIcon' => 'calculator']);
$manager = new FinanceManager((string) $_SESSION['user_id']);
$canWrite = (getRoleInfo()['access'] ?? 'none') === 'write';
if ($_SERVER['REQUEST_METHOD'] === 'POST') { require_csrf(); if (!$canWrite) { http_response_code(403); exit('Access denied.'); } $manager->addBudget($_POST); header('Location: budget.php?result=created'); exit; }
$budgets = $manager->getBudgets();
include dirname(__DIR__) . '/shared/header.php'; include dirname(__DIR__) . '/shared/sidebar.php';
?>
<div class="content-wrapper with-sidebar"><div class="container-fluid"><div class="main-content"><div class="d-flex flex-wrap justify-content-between align-items-center gap-2 mb-4"><div><h1 class="section-title mb-1"><i class="fas fa-chart-line"></i> Budget Planning</h1><p class="text-muted mb-0">Plan and record annual budget allocations.</p></div></div><?php if (isset($_GET['result'])): ?><div class="alert alert-success">Budget allocation saved.</div><?php endif; ?><?php if ($canWrite): ?><div class="card mb-4"><div class="card-header"><strong>New Allocation</strong></div><div class="card-body"><form method="post" class="row g-3"><?= csrf_field() ?><div class="col-md-3"><label class="form-label">Fiscal year</label><input class="form-control" type="number" name="fiscal_year" value="<?= date('Y') ?>" required></div><div class="col-md-4"><label class="form-label">Category</label><input class="form-control" name="category" required></div><div class="col-md-3"><label class="form-label">Amount</label><input class="form-control" type="number" min="0" step="0.01" name="amount" required></div><div class="col-md-2 d-flex align-items-end"><button class="btn btn-primary w-100">Save allocation</button></div><div class="col-12"><label class="form-label">Notes</label><textarea class="form-control" name="notes" rows="2"></textarea></div></form></div></div><?php endif; ?><div class="card"><div class="card-header"><strong>Budget Allocations</strong></div><div class="table-responsive"><table class="table mb-0"><thead><tr><th>Year</th><th>Category</th><th>Amount</th><th>Notes</th></tr></thead><tbody><?php foreach ($budgets as $budget): ?><tr><td><?= $budget['fiscal_year'] ?></td><td><?= htmlspecialchars($budget['category']) ?></td><td>$<?= number_format((float) $budget['amount'], 2) ?></td><td><?= htmlspecialchars($budget['notes'] ?? '') ?></td></tr><?php endforeach; ?><?php if (!$budgets): ?><tr><td colspan="4" class="text-center text-muted py-4">No budget allocations recorded.</td></tr><?php endif; ?></tbody></table></div></div></div></div></div>
<?php include dirname(__DIR__) . '/shared/footer.php'; ?>