<?php
require_once dirname(__DIR__) . '/shared/csrf.php';
if (session_status() === PHP_SESSION_NONE) session_start();
require_once dirname(__DIR__) . '/shared/rbac.php';
require_once dirname(__DIR__) . '/shared/branch_owned_records.php';
if (!isset($_SESSION['user_id'])) { header('Location: /Armis2/login.php?return_url='.urlencode($_SERVER['REQUEST_URI']??'')); exit; }
requireModuleAccess('training');
$pdo=getDbConnection();
$canWrite=(($_SESSION['role']??'')==='admin') || hasPermission(PERM_MANAGE_EDUCATION);
$message=''; $error='';
if($_SERVER['REQUEST_METHOD']==='POST'){
    require_csrf();
    if(!$canWrite){http_response_code(403);exit('Access denied. Training education-management permission is required.');}
    try{
        $action=$_POST['action']??'';
        if(in_array($action,['education_save','skills_save'],true)){
            $svc=trim((string)($_POST['svcNo']??''));
            if(!armisScopedStaffExists($pdo,$svc)) throw new RuntimeException('The selected personnel record is outside your branch scope or does not exist.');
            if($action==='education_save'){
                $id=(int)($_POST['id']??0); $inst=trim((string)($_POST['institution']??'')); $qual=trim((string)($_POST['qualification']??''));
                if($inst===''||$qual==='') throw new RuntimeException('Institution and qualification are required.');
                $data=[$inst,$qual,trim((string)($_POST['level']??'')),trim((string)($_POST['field_of_study']??'')),($_POST['year_started']??'')!==''?(int)$_POST['year_started']:null,($_POST['year_completed']??'')!==''?(int)$_POST['year_completed']:null,trim((string)($_POST['grade_obtained']??'')),trim((string)($_POST['status']??'Completed')),(int)!empty($_POST['is_highest_qualification'])];
                if($id){$st=$pdo->prepare('UPDATE staff_education SET institution=?,qualification=?,level=?,field_of_study=?,year_started=?,year_completed=?,grade_obtained=?,status=?,is_highest_qualification=? WHERE id=? AND svcNo=?');$st->execute([...$data,$id,$svc]);$message='Education record updated successfully.';}else{$st=$pdo->prepare('INSERT INTO staff_education (svcNo,institution,qualification,level,field_of_study,year_started,year_completed,grade_obtained,status,is_highest_qualification) VALUES (?,?,?,?,?,?,?,?,?,?)');$st->execute([$svc,...$data]);$message='Education record added successfully.';}
            } elseif($action==='course_record_save') {
                $svc=trim((string)($_POST['svcNo']??'')); if(!armisScopedStaffExists($pdo,$svc)) throw new RuntimeException('The selected personnel record is outside your branch scope or does not exist.');
                $id=(int)($_POST['id']??0); $inst=trim((string)($_POST['instId']??'')); $cse=trim((string)($_POST['cseId']??''));
                if($inst==='' || $cse==='') throw new RuntimeException('Institution and course are required.');
                $q=$pdo->prepare('SELECT 1 FROM institution WHERE instId=? LIMIT 1'); $q->execute([$inst]); if(!$q->fetchColumn()) throw new RuntimeException('Selected institution does not exist.');
                $q=$pdo->prepare('SELECT 1 FROM course WHERE cseId=? LIMIT 1'); $q->execute([$cse]); if(!$q->fetchColumn()) throw new RuntimeException('Selected course does not exist.');
                $data=[$inst,$cse,trim((string)($_POST['qualification']??'')),($_POST['cseStart']??'')?:null,($_POST['cseEnd']??'')?:null,trim((string)($_POST['grade']??'')),trim((string)($_POST['result']??'')),(int)!empty($_POST['isHighest']),trim((string)($_POST['authID']??''))];
                if($id){$q=$pdo->prepare('UPDATE staff_course SET instId=?,cseId=?,qualification=?,cseStart=?,cseEnd=?,grade=?,result=?,isHighest=?,authID=? WHERE id=? AND svcNo=?');$q->execute([...$data,$id,$svc]);$message='Course record updated successfully.';}else{$q=$pdo->prepare('INSERT INTO staff_course (svcNo,instId,cseId,qualification,cseStart,cseEnd,grade,result,isHighest,authID) VALUES (?,?,?,?,?,?,?,?,?,?)');$q->execute([$svc,...$data]);$message='Course record added successfully.';}
            } elseif($action==='course_record_delete') {
                $svc=trim((string)($_POST['svcNo']??'')); if(!armisScopedStaffExists($pdo,$svc)) throw new RuntimeException('Personnel is outside your branch scope.'); $q=$pdo->prepare('DELETE FROM staff_course WHERE id=? AND svcNo=?'); $q->execute([(int)$_POST['id'],$svc]); $message='Course record removed successfully.';
            } else {
                $id=(int)($_POST['id']??0);$course=trim((string)($_POST['course_name']??''));if($course==='')throw new RuntimeException('Course or skill name is required.');
                $data=[$course,trim((string)($_POST['course_type']??'')),trim((string)($_POST['institution']??'')),($_POST['startDate']??'')?:null,($_POST['endDate']??'')?:null,($_POST['duration_days']??'')!==''?(int)$_POST['duration_days']:null,trim((string)($_POST['certificateNumber']??'')),trim((string)($_POST['grade_obtained']??'')),trim((string)($_POST['location']??'')),($_POST['cost']??'')!==''?(float)$_POST['cost']:null,trim((string)($_POST['sponsored_by']??'')),trim((string)($_POST['certification_status']??''))];
                if($id){$st=$pdo->prepare('UPDATE staff_skills SET course_name=?,course_type=?,institution=?,startDate=?,endDate=?,duration_days=?,certificateNumber=?,grade_obtained=?,location=?,cost=?,sponsored_by=?,certification_status=? WHERE id=? AND svcNo=?');$st->execute([...$data,$id,$svc]);$message='Training/skill record updated successfully.';}else{$st=$pdo->prepare('INSERT INTO staff_skills (svcNo,course_name,course_type,institution,startDate,endDate,duration_days,certificateNumber,grade_obtained,location,cost,sponsored_by,certification_status) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?)');$st->execute([$svc,...$data]);$message='Training/skill record added successfully.';}
            }
        } elseif($action==='education_delete'||$action==='skills_delete'){
            $svc=trim((string)($_POST['svcNo']??''));if(!armisScopedStaffExists($pdo,$svc))throw new RuntimeException('Personnel is outside your branch scope.');$table=$action==='education_delete'?'staff_education':'staff_skills';$st=$pdo->prepare("DELETE FROM {$table} WHERE id=? AND svcNo=?");$st->execute([(int)$_POST['id'],$svc]);$message='Record removed successfully.';
        } elseif($action==='master_course_save'){
            $id=trim((string)($_POST['cseId']??''));if($id==='')throw new RuntimeException('Course ID is required.');$st=$pdo->prepare('INSERT INTO course (cseId,cseType,cseLevel,createdBy) VALUES (?,?,?,?) ON DUPLICATE KEY UPDATE cseType=VALUES(cseType),cseLevel=VALUES(cseLevel)');$st->execute([$id,$_POST['cseType']?:null,$_POST['cseLevel']?:null,(string)($_SESSION['user_id']??'')]);$message='Education course master record saved.';
        } elseif($action==='master_institution_save'){
            $id=trim((string)($_POST['instId']??''));if($id==='')throw new RuntimeException('Institution name/ID is required.');$st=$pdo->prepare('INSERT INTO institution (instId,instLoc,instType,instCountry,createdBy) VALUES (?,?,?,?,?) ON DUPLICATE KEY UPDATE instLoc=VALUES(instLoc),instType=VALUES(instType),instCountry=VALUES(instCountry)');$st->execute([$id,trim((string)($_POST['instLoc']??'')),$_POST['instType']?:null,trim((string)($_POST['instCountry']??'')),(string)($_SESSION['user_id']??'')]);$message='Institution master record saved.';
        }
    }catch(Throwable $e){$error=$e->getMessage();}
}
[$scopeSql,$scopeParams]=armisScopedStaffWhere('s');$st=$pdo->prepare("SELECT s.svcNo,s.fName,s.mName,s.lName,s.rankId,s.unitId FROM staff s WHERE {$scopeSql} AND s.svcStatus='Active' ORDER BY s.lName,s.fName,s.svcNo");$st->execute($scopeParams);$personnel=$st->fetchAll(PDO::FETCH_ASSOC);
$selectedSvc=trim((string)($_GET['svcNo']??$_POST['svcNo']??''));$selected=$selectedSvc?armisScopedStaffExists($pdo,$selectedSvc):null;if(!$selected&&!empty($personnel)){$selected=$personnel[0];$selectedSvc=$selected['svcNo'];}
$education=$skills=$staffCourses=[];if($selected){$st=$pdo->prepare('SELECT * FROM staff_course WHERE svcNo=? ORDER BY cseEnd DESC,id DESC');$st->execute([$selectedSvc]);$staffCourses=$st->fetchAll(PDO::FETCH_ASSOC);$st=$pdo->prepare('SELECT * FROM staff_education WHERE svcNo=? ORDER BY year_completed DESC,id DESC');$st->execute([$selectedSvc]);$education=$st->fetchAll(PDO::FETCH_ASSOC);$st=$pdo->prepare('SELECT * FROM staff_skills WHERE svcNo=? ORDER BY startDate DESC,id DESC');$st->execute([$selectedSvc]);$skills=$st->fetchAll(PDO::FETCH_ASSOC);}
$courses=$pdo->query('SELECT cseId,cseType,cseLevel,createdBy,dateCreated FROM course ORDER BY cseId')->fetchAll(PDO::FETCH_ASSOC);$institutions=$pdo->query('SELECT instId,instLoc,instType,instCountry,createdBy,dateCreated FROM institution ORDER BY instId')->fetchAll(PDO::FETCH_ASSOC);
$pageTitle='Education & Training Management';$moduleName='Training';$moduleIcon='graduation-cap';$currentPage='education';require_once __DIR__.'/includes/sidebar_nav.php';require_once dirname(__DIR__).'/shared/header.php';require_once dirname(__DIR__).'/shared/sidebar.php';
?>
<div class="content-wrapper with-sidebar"><div class="container-fluid"><div class="main-content"><div class="d-flex flex-wrap justify-content-between align-items-center gap-2 mb-4"><div><h1 class="section-title mb-1"><i class="fas fa-graduation-cap"></i> Education &amp; Training Management</h1><p class="text-muted mb-0">Maintain personnel education, professional training, skills, courses and institutions within the Training module.</p></div></div>
<?php if($message):?><div class="alert alert-success"><i class="fas fa-check-circle"></i> <?=htmlspecialchars($message)?></div><?php endif;?><?php if($error):?><div class="alert alert-danger"><i class="fas fa-exclamation-triangle"></i> <?=htmlspecialchars($error)?></div><?php endif;?>
<div class="card shadow-sm mb-4"><div class="card-body"><div class="row g-3 align-items-end"><div class="col-md-8"><label class="form-label fw-semibold">Personnel</label><select class="form-select" onchange="location.href='education.php?svcNo='+encodeURIComponent(this.value)"><option value="">Select personnel</option><?php foreach($personnel as $p):?><option value="<?=htmlspecialchars($p['svcNo'])?>" <?=$selectedSvc===$p['svcNo']?'selected':''?>><?=htmlspecialchars($p['svcNo'].' — '.trim($p['lName'].' '.$p['fName'].' '.$p['mName']))?></option><?php endforeach;?></select></div><div class="col-md-4"><div class="small text-muted">Current Unit</div><div class="fw-semibold"><?=htmlspecialchars($selected['unitId']??'Not assigned')?></div></div></div></div></div>
<ul class="nav nav-tabs mb-3"><li class="nav-item"><button class="nav-link active" data-bs-toggle="tab" data-bs-target="#edu" type="button"><i class="fas fa-user-graduate"></i> Education</button></li><li class="nav-item"><button class="nav-link" data-bs-toggle="tab" data-bs-target="#coursesDone" type="button"><i class="fas fa-book-reader"></i> Course Records</button></li><li class="nav-item"><button class="nav-link" data-bs-toggle="tab" data-bs-target="#skills" type="button"><i class="fas fa-certificate"></i> Training &amp; Skills</button></li><li class="nav-item"><button class="nav-link" data-bs-toggle="tab" data-bs-target="#masters" type="button"><i class="fas fa-database"></i> Courses &amp; Institutions</button></li></ul>
<div class="tab-content"><div class="tab-pane fade show active" id="edu"><div class="card"><div class="card-header d-flex justify-content-between"><strong>Education Records</strong><?php if($canWrite&&$selected):?><button class="btn btn-primary btn-sm" data-bs-toggle="modal" data-bs-target="#eduModal"><i class="fas fa-plus"></i> Add Education</button><?php endif;?></div><div class="table-responsive"><table class="table table-hover mb-0"><thead><tr><th>Institution</th><th>Qualification</th><th>Level</th><th>Field</th><th>Years</th><th>Grade</th><th>Highest</th><?php if($canWrite):?><th></th><?php endif;?></tr></thead><tbody><?php foreach($education as $r):?><tr><td><?=htmlspecialchars($r['institution'])?></td><td><?=htmlspecialchars($r['qualification'])?></td><td><?=htmlspecialchars($r['level'])?></td><td><?=htmlspecialchars($r['field_of_study'])?></td><td><?=htmlspecialchars(($r['year_started']??'').' — '.($r['year_completed']??''))?></td><td><?=htmlspecialchars($r['grade_obtained'])?></td><td><?=$r['is_highest_qualification']?'Yes':'No'?></td><?php if($canWrite):?><td><button class="btn btn-outline-primary btn-sm" onclick='editEducation(<?=json_encode($r,JSON_HEX_APOS|JSON_HEX_QUOT)?>)'>Edit</button></td><?php endif;?></tr><?php endforeach;?><?php if(!$education):?><tr><td colspan="8" class="text-center text-muted py-4">No education records for this personnel.</td></tr><?php endif;?></tbody></table></div></div></div>
<div class="tab-pane fade" id="coursesDone"><div class="card"><div class="card-header d-flex justify-content-between"><strong>Completed / Attended Courses</strong><?php if($canWrite&&$selected):?><button class="btn btn-primary btn-sm" data-bs-toggle="modal" data-bs-target="#courseRecordModal"><i class="fas fa-plus"></i> Add Course Record</button><?php endif;?></div><div class="table-responsive"><table class="table table-hover mb-0"><thead><tr><th>Institution</th><th>Course</th><th>Qualification</th><th>Start</th><th>End</th><th>Grade</th><th>Result</th><?php if($canWrite):?><th></th><?php endif;?></tr></thead><tbody><?php foreach($staffCourses as $r):?><tr><td><?=htmlspecialchars($r['instId'])?></td><td><?=htmlspecialchars($r['cseId'])?></td><td><?=htmlspecialchars($r['qualification'])?></td><td><?=htmlspecialchars($r['cseStart'])?></td><td><?=htmlspecialchars($r['cseEnd'])?></td><td><?=htmlspecialchars($r['grade'])?></td><td><?=htmlspecialchars($r['result'])?></td><?php if($canWrite):?><td><button class="btn btn-outline-primary btn-sm" onclick='editCourseRecord(<?=json_encode($r,JSON_HEX_APOS|JSON_HEX_QUOT)?>)'>Edit</button></td><?php endif;?></tr><?php endforeach;?><?php if(!$staffCourses):?><tr><td colspan="8" class="text-center text-muted py-4">No course records for this personnel.</td></tr><?php endif;?></tbody></table></div></div></div>
<div class="tab-pane fade" id="skills"><div class="card"><div class="card-header d-flex justify-content-between"><strong>Training &amp; Skills</strong><?php if($canWrite&&$selected):?><button class="btn btn-primary btn-sm" data-bs-toggle="modal" data-bs-target="#skillModal"><i class="fas fa-plus"></i> Add Training / Skill</button><?php endif;?></div><div class="table-responsive"><table class="table table-hover mb-0"><thead><tr><th>Course / Skill</th><th>Type</th><th>Institution</th><th>Start</th><th>End</th><th>Status</th><?php if($canWrite):?><th></th><?php endif;?></tr></thead><tbody><?php foreach($skills as $r):?><tr><td><?=htmlspecialchars($r['course_name'])?></td><td><?=htmlspecialchars($r['course_type'])?></td><td><?=htmlspecialchars($r['institution'])?></td><td><?=htmlspecialchars($r['startDate'])?></td><td><?=htmlspecialchars($r['endDate'])?></td><td><?=htmlspecialchars($r['certification_status'])?></td><?php if($canWrite):?><td><button class="btn btn-outline-primary btn-sm" onclick='editSkill(<?=json_encode($r,JSON_HEX_APOS|JSON_HEX_QUOT)?>)'>Edit</button></td><?php endif;?></tr><?php endforeach;?><?php if(!$skills):?><tr><td colspan="7" class="text-center text-muted py-4">No training/skill records for this personnel.</td></tr><?php endif;?></tbody></table></div></div></div>
<div class="tab-pane fade" id="masters"><div class="row g-4"><div class="col-lg-6"><div class="card"><div class="card-header d-flex justify-content-between"><strong>Education Courses</strong><?php if($canWrite):?><button class="btn btn-primary btn-sm" data-bs-toggle="modal" data-bs-target="#courseModal"><i class="fas fa-plus"></i> Add Course</button><?php endif;?></div><div class="table-responsive"><table class="table table-sm mb-0"><thead><tr><th>Course ID</th><th>Type</th><th>Level</th><th></th></tr></thead><tbody><?php foreach($courses as $c):?><tr><td><?=htmlspecialchars($c['cseId'])?></td><td><?=htmlspecialchars($c['cseType'])?></td><td><?=htmlspecialchars($c['cseLevel'])?></td><td><?php if($canWrite):?><button class="btn btn-outline-primary btn-sm" onclick='editMasterCourse(<?=json_encode($c,JSON_HEX_APOS|JSON_HEX_QUOT)?>)'>Edit</button><?php endif;?></td></tr><?php endforeach;?></tbody></table></div></div></div><div class="col-lg-6"><div class="card"><div class="card-header d-flex justify-content-between"><strong>Institutions</strong><?php if($canWrite):?><button class="btn btn-primary btn-sm" data-bs-toggle="modal" data-bs-target="#instModal"><i class="fas fa-plus"></i> Add Institution</button><?php endif;?></div><div class="table-responsive"><table class="table table-sm mb-0"><thead><tr><th>Institution</th><th>Location</th><th>Type</th><th>Country</th><th></th></tr></thead><tbody><?php foreach($institutions as $i):?><tr><td><?=htmlspecialchars($i['instId'])?></td><td><?=htmlspecialchars($i['instLoc'])?></td><td><?=htmlspecialchars($i['instType'])?></td><td><?=htmlspecialchars($i['instCountry'])?></td><td><?php if($canWrite):?><button class="btn btn-outline-primary btn-sm" onclick='editMasterInstitution(<?=json_encode($i,JSON_HEX_APOS|JSON_HEX_QUOT)?>)'>Edit</button><?php endif;?></td></tr><?php endforeach;?></tbody></table></div></div></div></div></div></div>
<?php if($canWrite&&$selected):?>
<div class="modal fade" id="eduModal"><div class="modal-dialog modal-lg"><div class="modal-content"><form method="post"><input type="hidden" name="csrf" value="<?=htmlspecialchars(csrf_token())?>"><input type="hidden" name="action" value="education_save"><input type="hidden" name="svcNo" value="<?=htmlspecialchars($selectedSvc)?>"><input type="hidden" name="id" id="edu_id"><div class="modal-header"><h5 class="modal-title">Education Record</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="row g-3"><div class="col-md-6"><label class="form-label">Institution *</label><input name="institution" id="edu_inst" class="form-control" required></div><div class="col-md-6"><label class="form-label">Qualification *</label><input name="qualification" id="edu_qual" class="form-control" required></div><div class="col-md-4"><label class="form-label">Level</label><input name="level" id="edu_level" class="form-control"></div><div class="col-md-8"><label class="form-label">Field of Study</label><input name="field_of_study" id="edu_field" class="form-control"></div><div class="col-md-3"><label class="form-label">Year Started</label><input type="number" name="year_started" id="edu_start" class="form-control"></div><div class="col-md-3"><label class="form-label">Year Completed</label><input type="number" name="year_completed" id="edu_end" class="form-control"></div><div class="col-md-3"><label class="form-label">Grade</label><input name="grade_obtained" id="edu_grade" class="form-control"></div><div class="col-md-3"><label class="form-label">Status</label><input name="status" id="edu_status" value="Completed" class="form-control"></div><div class="col-12"><div class="form-check"><input type="checkbox" name="is_highest_qualification" value="1" id="edu_highest" class="form-check-input"><label for="edu_highest" class="form-check-label">Highest qualification</label></div></div></div></div><div class="modal-footer"><button class="btn btn-primary">Save Education</button></div></form></div></div></div>
<div class="modal fade" id="courseRecordModal"><div class="modal-dialog modal-lg"><div class="modal-content"><form method="post"><input type="hidden" name="csrf" value="<?=htmlspecialchars(csrf_token())?>"><input type="hidden" name="action" value="course_record_save"><input type="hidden" name="svcNo" value="<?=htmlspecialchars($selectedSvc)?>"><input type="hidden" name="id" id="cr_id"><div class="modal-header"><h5 class="modal-title">Course Record</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="row g-3"><div class="col-md-6"><label class="form-label">Institution *</label><select name="instId" id="cr_inst" class="form-select" required><option value="">Select institution</option><?php foreach($institutions as $i):?><option value="<?=htmlspecialchars($i['instId'])?>"><?=htmlspecialchars($i['instId'])?></option><?php endforeach;?></select></div><div class="col-md-6"><label class="form-label">Course *</label><select name="cseId" id="cr_course" class="form-select" required><option value="">Select course</option><?php foreach($courses as $c):?><option value="<?=htmlspecialchars($c['cseId'])?>"><?=htmlspecialchars($c['cseId'].' — '.($c['cseLevel']??''))?></option><?php endforeach;?></select></div><div class="col-md-6"><label class="form-label">Qualification</label><input name="qualification" id="cr_qual" class="form-control"></div><div class="col-md-3"><label class="form-label">Start</label><input type="date" name="cseStart" id="cr_start" class="form-control"></div><div class="col-md-3"><label class="form-label">End</label><input type="date" name="cseEnd" id="cr_end" class="form-control"></div><div class="col-md-3"><label class="form-label">Grade</label><input name="grade" id="cr_grade" class="form-control"></div><div class="col-md-3"><label class="form-label">Result</label><input name="result" id="cr_result" class="form-control"></div><div class="col-md-3"><label class="form-label">Authority Ref.</label><input name="authID" id="cr_auth" class="form-control"></div><div class="col-md-3"><div class="form-check mt-4"><input type="checkbox" name="isHighest" value="1" id="cr_highest" class="form-check-input"><label for="cr_highest" class="form-check-label">Highest</label></div></div></div></div><div class="modal-footer"><button class="btn btn-primary">Save Course Record</button></div></form></div></div></div>
<div class="modal fade" id="skillModal"><div class="modal-dialog modal-lg"><div class="modal-content"><form method="post"><input type="hidden" name="csrf" value="<?=htmlspecialchars(csrf_token())?>"><input type="hidden" name="action" value="skills_save"><input type="hidden" name="svcNo" value="<?=htmlspecialchars($selectedSvc)?>"><input type="hidden" name="id" id="skill_id"><div class="modal-header"><h5 class="modal-title">Training / Skill Record</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="row g-3"><div class="col-md-6"><label class="form-label">Course / Skill *</label><input name="course_name" id="skill_name" class="form-control" required></div><div class="col-md-6"><label class="form-label">Type</label><input name="course_type" id="skill_type" class="form-control"></div><div class="col-md-6"><label class="form-label">Institution</label><input name="institution" id="skill_inst" class="form-control"></div><div class="col-md-3"><label class="form-label">Start</label><input type="date" name="startDate" id="skill_start" class="form-control"></div><div class="col-md-3"><label class="form-label">End</label><input type="date" name="endDate" id="skill_end" class="form-control"></div><div class="col-md-4"><label class="form-label">Certificate No.</label><input name="certificateNumber" id="skill_cert" class="form-control"></div><div class="col-md-4"><label class="form-label">Status</label><input name="certification_status" id="skill_status" class="form-control"></div><div class="col-md-4"><label class="form-label">Sponsored By</label><input name="sponsored_by" id="skill_sponsor" class="form-control"></div><div class="col-12"><label class="form-label">Notes / Location</label><input name="location" id="skill_location" class="form-control"></div></div></div><div class="modal-footer"><button class="btn btn-primary">Save Training Record</button></div></form></div></div></div>
<div class="modal fade" id="courseModal"><div class="modal-dialog"><div class="modal-content"><form method="post"><input type="hidden" name="csrf" value="<?=htmlspecialchars(csrf_token())?>"><input type="hidden" name="action" value="master_course_save"><div class="modal-header"><h5 class="modal-title">Education Course</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><label class="form-label">Course ID *</label><input name="cseId" id="master_cseId" class="form-control mb-3" required><label class="form-label">Type</label><select name="cseType" class="form-select mb-3"><option value="">Select</option><option>Military</option><option>Civil</option></select><label class="form-label">Level</label><select name="cseLevel" class="form-select"><option value="">Select</option><option>Diploma</option><option>Bachelors</option><option>Masters</option><option>PhD</option></select></div><div class="modal-footer"><button class="btn btn-primary">Save Course</button></div></form></div></div></div>
<div class="modal fade" id="instModal"><div class="modal-dialog"><div class="modal-content"><form method="post"><input type="hidden" name="csrf" value="<?=htmlspecialchars(csrf_token())?>"><input type="hidden" name="action" value="master_institution_save"><div class="modal-header"><h5 class="modal-title">Institution</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><label class="form-label">Institution Name / ID *</label><input name="instId" id="master_instId" class="form-control mb-3" required><label class="form-label">Location</label><input name="instLoc" class="form-control mb-3"><label class="form-label">Type</label><select name="instType" class="form-select mb-3"><option value="">Select</option><option>Local</option><option>International</option></select><label class="form-label">Country</label><input name="instCountry" class="form-control"></div><div class="modal-footer"><button class="btn btn-primary">Save Institution</button></div></form></div></div></div><?php endif;?>
</div></div></div>
<script>function editMasterCourse(r){document.getElementById('master_cseId').value=r.cseId||'';document.querySelector('#courseModal select[name=\"cseType\"]').value=r.cseType||'';document.querySelector('#courseModal select[name=\"cseLevel\"]').value=r.cseLevel||'';new bootstrap.Modal(document.getElementById('courseModal')).show()}function editMasterInstitution(r){document.getElementById('master_instId').value=r.instId||'';document.querySelector('#instModal input[name=\"instLoc\"]').value=r.instLoc||'';document.querySelector('#instModal select[name=\"instType\"]').value=r.instType||'';document.querySelector('#instModal input[name=\"instCountry\"]').value=r.instCountry||'';new bootstrap.Modal(document.getElementById('instModal')).show()}function editEducation(r){for(const [id,k] of Object.entries({edu_id:'id',edu_inst:'institution',edu_qual:'qualification',edu_level:'level',edu_field:'field_of_study',edu_start:'year_started',edu_end:'year_completed',edu_grade:'grade_obtained',edu_status:'status'})){document.getElementById(id).value=r[k]??''}document.getElementById('edu_highest').checked=!!Number(r.is_highest_qualification);new bootstrap.Modal(document.getElementById('eduModal')).show()}function editCourseRecord(r){for(const [id,k] of Object.entries({cr_id:'id',cr_inst:'instId',cr_course:'cseId',cr_qual:'qualification',cr_start:'cseStart',cr_end:'cseEnd',cr_grade:'grade',cr_result:'result',cr_auth:'authID'})){document.getElementById(id).value=r[k]??''}document.getElementById('cr_highest').checked=!!Number(r.isHighest);new bootstrap.Modal(document.getElementById('courseRecordModal')).show()}function editSkill(r){for(const [id,k] of Object.entries({skill_id:'id',skill_name:'course_name',skill_type:'course_type',skill_inst:'institution',skill_start:'startDate',skill_end:'endDate',skill_cert:'certificateNumber',skill_status:'certification_status',skill_sponsor:'sponsored_by',skill_location:'location'})){document.getElementById(id).value=r[k]??''}new bootstrap.Modal(document.getElementById('skillModal')).show()}</script>
<?php require_once dirname(__DIR__).'/shared/footer.php'; ?>
