<?php
/**
 * ARMIS System Administration — Role & Branch Assignment
 *
 * CHANGELOG (branch-scoping upgrade): this file previously queried a
 * `users` table that does not exist anywhere in the ARMIS schema (login
 * credentials, role, and account status all live on `staff` — see
 * armis1.sql). Every query here ran against a phantom table and would have
 * thrown a fatal PDO exception the moment this page was hit. It has been
 * rewritten end-to-end against the real `staff` table, and extended to be
 * the canonical screen for assigning the new branch-scoped roles
 * (cc/soi/soii/soiii/dg/ag) together with a Branch, which is what actually
 * grants a person their record-alteration scope (see shared/rbac.php).
 */

if (session_status() === PHP_SESSION_NONE) {
    session_start();
}

require_once dirname(__DIR__) . '/config.php';
require_once dirname(__DIR__) . '/shared/database_connection.php';
require_once dirname(__DIR__) . '/shared/rbac.php';
require_once dirname(__DIR__) . '/shared/password_policy.php';

function armisCredentialStoreDir(): string
{
    $dir = dirname(__DIR__) . '/cache/generated_credentials';
    if (!is_dir($dir)) {
        @mkdir($dir, 0700, true);
    }
    return $dir;
}

function armisStoreGeneratedCredentials(array $credentials): ?string
{
    if (!$credentials) {
        return null;
    }
    $token = bin2hex(random_bytes(32));
    $path = armisCredentialStoreDir() . '/' . $token . '.json';
    $payload = json_encode([
        'created_at' => time(),
        'expires_at' => time() + 3600,
        'credentials' => array_values($credentials),
    ], JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES);
    if ($payload === false || @file_put_contents($path, $payload, LOCK_EX) === false) {
        return null;
    }
    @chmod($path, 0600);
    return $token;
}

function armisLoadGeneratedCredentials(): array
{
    $token = $_SESSION['armis_generated_credentials_token'] ?? '';
    if ($token === '' || !preg_match('/^[a-f0-9]{64}$/', $token)) {
        // Backward compatibility with credentials generated by the previous session-based version.
        return is_array($_SESSION['armis_generated_credentials'] ?? null) ? $_SESSION['armis_generated_credentials'] : [];
    }
    $path = armisCredentialStoreDir() . '/' . $token . '.json';
    if (!is_file($path)) {
        unset($_SESSION['armis_generated_credentials_token']);
        return [];
    }
    $raw = @file_get_contents($path);
    $data = is_string($raw) ? json_decode($raw, true) : null;
    if (!is_array($data) || !isset($data['expires_at'], $data['credentials']) || (int)$data['expires_at'] < time()) {
        @unlink($path);
        unset($_SESSION['armis_generated_credentials_token']);
        return [];
    }
    return is_array($data['credentials']) ? $data['credentials'] : [];
}

function armisClearGeneratedCredentials(): void
{
    $token = $_SESSION['armis_generated_credentials_token'] ?? '';
    if (is_string($token) && preg_match('/^[a-f0-9]{64}$/', $token)) {
        @unlink(armisCredentialStoreDir() . '/' . $token . '.json');
    }
    unset($_SESSION['armis_generated_credentials_token'], $_SESSION['armis_generated_credentials']);
}

function armisGenerateStaffTempPassword(): string
{
    $upper = 'ABCDEFGHJKLMNPQRSTUVWXYZ';
    $lower = 'abcdefghijkmnopqrstuvwxyz';
    $digits = '23456789';
    $special = '@#$%';
    $pool = $upper . $lower . $digits . $special;
    $password = $upper[random_int(0, strlen($upper) - 1)]
        . $lower[random_int(0, strlen($lower) - 1)]
        . $digits[random_int(0, strlen($digits) - 1)]
        . $special[random_int(0, strlen($special) - 1)];
    for ($i = 4; $i < 12; $i++) {
        $password .= $pool[random_int(0, strlen($pool) - 1)];
    }
    $chars = str_split($password);
    for ($i = count($chars) - 1; $i > 0; $i--) {
        $j = random_int(0, $i);
        [$chars[$i], $chars[$j]] = [$chars[$j], $chars[$i]];
    }
    return implode('', $chars);
}

/**
 * Create a login directly on the canonical ARMIS staff table.
 * This function intentionally does not reference or depend on a users table.
 */
function armisCreateStaffAccount(PDO $pdo, string $svcNo, string $firstName, string $lastName, string $email = ''): array
{
    $svcNo = trim($svcNo);
    if ($svcNo === '') {
        return ['success' => false, 'message' => 'Service number is empty.'];
    }

    try {
        $check = $pdo->prepare('SELECT svcNo, username, password FROM staff WHERE svcNo = ? LIMIT 1');
        $check->execute([$svcNo]);
        $staff = $check->fetch(PDO::FETCH_ASSOC);
        if (!$staff) {
            return ['success' => false, 'message' => 'Staff record not found in staff table.'];
        }

        if (trim((string)($staff['username'] ?? '')) !== '' || trim((string)($staff['password'] ?? '')) !== '') {
            return ['success' => false, 'message' => 'This staff member already has an account.'];
        }

        // The service number is the canonical and deterministic username.
        // It is also accepted by authenticateUser() as a login identifier.
        $username = substr(preg_replace('/[^A-Za-z0-9._-]/', '', $svcNo), 0, 25);
        if ($username === '') {
            return ['success' => false, 'message' => 'Unable to derive a valid username from the service number.'];
        }

        $unique = $pdo->prepare('SELECT svcNo FROM staff WHERE username = ? AND svcNo <> ? LIMIT 1');
        $unique->execute([$username, $svcNo]);
        if ($unique->fetchColumn()) {
            return ['success' => false, 'message' => 'The service number is already assigned as a username to another staff record.'];
        }

        // Use the existing secure generator only for the temporary password;
        // the actual account write below is explicitly against staff.
        $tempPassword = armisGenerateStaffTempPassword();
        $hash = password_hash($tempPassword, PASSWORD_DEFAULT);
        if ($hash === false) {
            return ['success' => false, 'message' => 'Unable to hash the temporary password.'];
        }

        $sql = "UPDATE staff
                   SET username = ?, password = ?, accStatus = 'Active',
                       isFirstLogin = 1, passwordChangedAt = NULL
                 WHERE svcNo = ?
                   AND (username IS NULL OR username = '')
                   AND (password IS NULL OR password = '')";
        $update = $pdo->prepare($sql);
        $update->execute([$username, $hash, $svcNo]);

        if ($update->rowCount() !== 1) {
            $verify = $pdo->prepare('SELECT username, password FROM staff WHERE svcNo = ? LIMIT 1');
            $verify->execute([$svcNo]);
            $after = $verify->fetch(PDO::FETCH_ASSOC);
            if ($after && (!empty($after['username']) || !empty($after['password']))) {
                return ['success' => false, 'message' => 'Account was created concurrently or credentials now exist for this staff record.'];
            }
            return ['success' => false, 'message' => 'UPDATE staff affected 0 rows. No users table is involved. Verify the live staff record and database permissions.'];
        }

        return [
            'success' => true,
            'svcNo' => $svcNo,
            'username' => $username,
            'password' => $tempPassword,
            'message' => 'Account created directly in staff.username and staff.password.'
        ];
    } catch (PDOException $e) {
        $info = $e->errorInfo ?? [];
        $state = $info[0] ?? $e->getCode();
        $driver = $info[1] ?? '';
        $detail = $info[2] ?? $e->getMessage();
        error_log("ARMIS staff account creation failed for {$svcNo}: SQLSTATE={$state} DRIVER={$driver} {$detail}");
        return ['success' => false, 'message' => "Database error [{$state}/{$driver}]: {$detail}"];
    }
}

try {
    $pdo = getDbConnection();
} catch (Exception $e) {
    error_log("Database connection failed in admin/users.php: " . $e->getMessage());
    die("Database connection failed. Please check your configuration.");
}

$pageTitle = "Role & Branch Assignment";
$moduleName = "System Admin";
$moduleIcon = "users";
$currentPage = "users";

require_once __DIR__ . '/includes/sidebar_nav.php';

if (!isset($_SESSION['user_id'])) {
    header('Location: ' . dirname($_SERVER['PHP_SELF']) . '/../login.php');
    exit();
}

requireModuleAccess('admin');
requireBranchAdmin(); // this page reassigns roles/branches - system-admin only, not just "admin module" viewers
logAccess('admin', 'users_view', true);

$message = '';
$messageType = '';
$generatedCredentials = armisLoadGeneratedCredentials();
$bulkSummary = ['created' => 0, 'existing' => 0, 'failed' => 0, 'total_active' => 0];
$bulkFailures = [];
$allRoles = getAllRoles(true);
$allBranches = getAllBranches(true);

if ($_SERVER['REQUEST_METHOD'] === 'POST' && isset($_POST['action'])) {
    $csrf = $_POST['csrf_token'] ?? '';
    if (!isset($_SESSION['csrf_token']) || !hash_equals($_SESSION['csrf_token'], $csrf)) {
        $message = "Invalid CSRF token. Please reload the page and try again.";
        $messageType = "danger";
    } else {
        try {
            switch ($_POST['action']) {
                case 'diagnose_account_creation':
                    $diagStmt = $pdo->query("SELECT svcNo, fName, lName, username, password FROM staff WHERE svcStatus = 'Active' AND (username IS NULL OR username = '') AND (password IS NULL OR password = '') ORDER BY svcNo LIMIT 1");
                    $diagPerson = $diagStmt->fetch(PDO::FETCH_ASSOC);
                    if (!$diagPerson) {
                        throw new Exception('No active personnel record is available for the account-creation diagnostic.');
                    }
                    $diagResult = armisCreateStaffAccount($pdo, 
                        (string)$diagPerson['svcNo'],
                        (string)($diagPerson['fName'] ?? ''),
                        (string)($diagPerson['lName'] ?? ''),
                        ''
                    );
                    if ($diagResult['success']) {
                        $generatedCredentials[] = [
                            'svcNo' => $diagResult['svcNo'],
                            'name' => trim(($diagPerson['fName'] ?? '') . ' ' . ($diagPerson['lName'] ?? '')),
                            'username' => $diagResult['username'],
                            'password' => $diagResult['password'],
                        ];
                        $message = 'Diagnostic succeeded: one active account was created successfully. This confirms the live database write path is working. You can now run the bulk operation.';
                        $messageType = 'success';
                    } else {
                        throw new Exception('Diagnostic failed for ' . $diagPerson['svcNo'] . ': ' . $diagResult['message']);
                    }
                    break;

                case 'create_active_users':
                    $activeStmt = $pdo->query("SELECT svcNo, fName, lName, officialEmail, username, password FROM staff WHERE svcStatus = 'Active' ORDER BY svcNo");
                    $activeStaff = $activeStmt->fetchAll(PDO::FETCH_ASSOC);
                    $bulkSummary['total_active'] = count($activeStaff);

                    foreach ($activeStaff as $person) {
                        // Never overwrite an existing account or password during bulk creation.
                        if (!empty($person['username']) && !empty($person['password'])) {
                            $bulkSummary['existing']++;
                            continue;
                        }

                        try {
                            $result = armisCreateStaffAccount($pdo,
                                (string)$person['svcNo'],
                                (string)($person['fName'] ?? ''),
                                (string)($person['lName'] ?? ''),
                                (string)($person['officialEmail'] ?? '')
                            );
                            if ($result['success']) {
                                $bulkSummary['created']++;
                                $generatedCredentials[] = [
                                    'svcNo' => $result['svcNo'],
                                    'name' => trim(($person['fName'] ?? '') . ' ' . ($person['lName'] ?? '')),
                                    'username' => $result['username'],
                                    'password' => $result['password'],
                                ];
                            } else {
                                $bulkSummary['failed']++;
                                error_log('ARMIS bulk account creation skipped ' . $person['svcNo'] . ': ' . $result['message']);
                                $bulkFailures[] = ['svcNo' => $person['svcNo'], 'name' => trim(($person['fName'] ?? '') . ' ' . ($person['lName'] ?? '')), 'reason' => $result['message']];
                            }
                        } catch (Throwable $accountError) {
                            $bulkSummary['failed']++;
                            error_log('ARMIS bulk account creation failed for ' . $person['svcNo'] . ': ' . $accountError->getMessage());
                            $bulkFailures[] = ['svcNo' => $person['svcNo'], 'name' => trim(($person['fName'] ?? '') . ' ' . ($person['lName'] ?? '')), 'reason' => $accountError->getMessage()];
                        }
                    }

                    $message = sprintf(
                        'Account creation complete: %d created, %d already had accounts, %d failed, from %d active personnel.',
                        $bulkSummary['created'], $bulkSummary['existing'], $bulkSummary['failed'], $bulkSummary['total_active']
                    );
                    $messageType = $bulkSummary['failed'] > 0 ? 'warning' : 'success';
                    $_SESSION['armis_bulk_failures'] = $bulkFailures;
                    armisClearGeneratedCredentials();
                    if ($generatedCredentials) {
                        $credentialToken = armisStoreGeneratedCredentials($generatedCredentials);
                        if ($credentialToken === null) {
                            throw new Exception('Accounts were created, but the temporary credential export store could not be written. Check the cache/generated_credentials directory permissions.');
                        }
                        $_SESSION['armis_generated_credentials_token'] = $credentialToken;
                    }
                    logAccess('admin', 'bulk_user_account_creation', true, sprintf(
                        'Created=%d Existing=%d Failed=%d Active=%d',
                        $bulkSummary['created'], $bulkSummary['existing'], $bulkSummary['failed'], $bulkSummary['total_active']
                    ));
                    break;

                case 'export_credentials':
                    $credentials = armisLoadGeneratedCredentials();
                    if (empty($credentials)) {
                        throw new Exception('There are no newly generated credentials available for export. The one-time export may already have been used or the temporary credential file expired.');
                    }
                    // Export is deliberately one-time: remove the temporary plaintext credential file
                    // immediately after loading it. No plaintext password is stored in the database.
                    armisClearGeneratedCredentials();
                    while (ob_get_level() > 0) { ob_end_clean(); }
                    header('Content-Type: text/csv; charset=utf-8');
                    header('Content-Disposition: attachment; filename=ARMIS_new_account_credentials_' . date('Ymd_His') . '.csv');
                    header('Cache-Control: no-store, no-cache, must-revalidate, max-age=0');
                    header('Pragma: no-cache');
                    $out = fopen('php://output', 'w');
                    fputcsv($out, ['Service Number', 'Staff Name', 'Username', 'Temporary Password']);
                    foreach ($credentials as $cred) {
                        fputcsv($out, [$cred['svcNo'], $cred['name'], $cred['username'], $cred['password']]);
                    }
                    fclose($out);
                    logAccess('admin', 'export_generated_credentials', true, 'Exported one-time credential CSV for ' . count($credentials) . ' newly created accounts.');
                    exit;

                case 'update_role_branch':
                    $svcNo = trim($_POST['svcNo'] ?? '');
                    $newRole = $_POST['new_role'] ?? '';
                    $newBranchId = ($_POST['new_branch_id'] ?? '') !== '' ? (int)$_POST['new_branch_id'] : null;

                    if (!isset($allRoles[$newRole])) {
                        throw new Exception("Unknown role selected.");
                    }
                    if ($allRoles[$newRole]['is_branch_assignable'] && !$newBranchId) {
                        throw new Exception("The role '" . $allRoles[$newRole]['name'] . "' requires a branch to be selected.");
                    }

                    $stmt = $pdo->prepare("UPDATE staff SET role = :role, branch_id = :branch_id WHERE svcNo = :svcNo");
                    $stmt->execute(['role' => $newRole, 'branch_id' => $newBranchId, 'svcNo' => $svcNo]);

                    $message = "Role/branch updated for $svcNo.";
                    $messageType = "success";
                    logAccess('admin', 'user_role_update', true, "Set svcNo=$svcNo role=$newRole branch_id=" . ($newBranchId ?? 'null'));
                    break;

                case 'toggle_status':
                    $svcNo = trim($_POST['svcNo'] ?? '');
                    $newStatus = $_POST['new_status'] ?? '';
                    if (!in_array($newStatus, ['Active', 'Inactive', 'Suspended', 'Pending'], true)) {
                        throw new Exception("Invalid status.");
                    }
                    $stmt = $pdo->prepare("UPDATE staff SET accStatus = :status WHERE svcNo = :svcNo");
                    $stmt->execute(['status' => $newStatus, 'svcNo' => $svcNo]);

                    $message = "Account status updated for $svcNo.";
                    $messageType = "success";
                    logAccess('admin', 'user_status_update', true, "Set svcNo=$svcNo accStatus=$newStatus");
                    break;

                case 'reset_password':
                    $svcNo = trim($_POST['svcNo'] ?? '');
                    if ($svcNo === '') throw new Exception('A service number is required.');
                    $stmt = $pdo->prepare('SELECT svcNo, fName, mName, lName, username, password, accStatus FROM staff WHERE svcNo = ? LIMIT 1');
                    $stmt->execute([$svcNo]);
                    $target = $stmt->fetch(PDO::FETCH_ASSOC);
                    if (!$target) throw new Exception('Staff account was not found.');
                    if (empty($target['username']) || empty($target['password'])) throw new Exception('This staff member does not have a complete login account. Create the account first.');

                    $tempPassword = armisGenerateStaffTempPassword();
                    // A generated password is overwhelmingly unlikely to be reused, but check it anyway.
                    if (armisPasswordWasUsedBefore($pdo, $svcNo, $tempPassword)) {
                        $tempPassword = armisGenerateStaffTempPassword();
                    }
                    $hashedPassword = password_hash($tempPassword, PASSWORD_DEFAULT);
                    if ($hashedPassword === false) throw new Exception('Unable to securely generate the reset password.');

                    // Ensure password-history DDL runs before the transaction. MySQL DDL can implicitly commit.
                    armisEnsurePasswordHistoryTable($pdo);
                    $pdo->beginTransaction();
                    try {
                        armisArchiveCurrentPassword($pdo, $svcNo, $target['password'], (string)($_SESSION['user_id'] ?? ''), 'administrative_reset');
                        $update = $pdo->prepare("UPDATE staff SET password = :pw, isFirstLogin = 1, passwordChangedAt = NULL WHERE svcNo = :svcNo");
                        $update->execute(['pw' => $hashedPassword, 'svcNo' => $svcNo]);
                        $pdo->commit();
                    } catch (Throwable $inner) {
                        if ($pdo->inTransaction()) $pdo->rollBack();
                        throw $inner;
                    }

                    $displayName = trim(($target['lName'] ?? '') . ' ' . ($target['fName'] ?? '') . ' ' . ($target['mName'] ?? ''));
                    $message = "Password reset for $svcNo. A temporary password was generated and the user must change it at next login.";
                    $messageType = "success";
                    $_SESSION['last_reset_credentials'] = [
                        'svcNo' => $svcNo,
                        'name' => $displayName,
                        'username' => $target['username'],
                        'password' => $tempPassword,
                        'created_at' => time(),
                    ];
                    logAccess('admin', 'password_reset', true, "Reset password for svcNo=$svcNo");
                    break;
            }
        } catch (Exception $e) {
            $message = "Error: " . $e->getMessage();
            $messageType = "danger";
            error_log("Admin Users Error: " . $e->getMessage());
        }
    }
}

if (!isset($_SESSION['csrf_token'])) {
    $_SESSION['csrf_token'] = bin2hex(random_bytes(32));
}
$csrfToken = $_SESSION['csrf_token'];

// Stats - all against the real staff table/columns
$userStats = ['total_users' => 0, 'active_users' => 0, 'privileged_users' => 0, 'new_users_month' => 0, 'active_personnel' => 0, 'active_without_accounts' => 0, 'password_reset_pending' => 0, 'login_attempts' => 0, 'successful_logins' => 0, 'failed_logins' => 0];
$userList = [];

try {
    $stmt = $pdo->query("SELECT
        COUNT(CASE WHEN username IS NOT NULL AND username <> '' AND password IS NOT NULL AND password <> '' THEN 1 END) AS total_users,
        COUNT(CASE WHEN username IS NOT NULL AND username <> '' AND password IS NOT NULL AND password <> '' AND accStatus = 'Active' THEN 1 END) AS active_users,
        COUNT(CASE WHEN username IS NOT NULL AND username <> '' AND password IS NOT NULL AND password <> '' AND role IS NOT NULL AND role <> 'user' THEN 1 END) AS privileged_users,
        COUNT(CASE WHEN username IS NOT NULL AND username <> '' AND dateCreated >= DATE_SUB(NOW(), INTERVAL 30 DAY) THEN 1 END) AS new_users_month,
        COUNT(CASE WHEN svcStatus = 'Active' THEN 1 END) AS active_personnel,
        COUNT(CASE WHEN svcStatus = 'Active' AND (username IS NULL OR username = '' OR password IS NULL OR password = '') THEN 1 END) AS active_without_accounts,
        COUNT(CASE WHEN username IS NOT NULL AND username <> '' AND password IS NOT NULL AND password <> '' AND (passwordChangedAt IS NULL OR isFirstLogin = 1) THEN 1 END) AS password_reset_pending
        FROM staff");
    $userStats = $stmt->fetch(PDO::FETCH_ASSOC);

    // Authentication activity is sourced from the real ARMIS activity_log.
    // login_success/login_failed are written by login.php; other activity_log
    // events are deliberately excluded so page visits cannot inflate this KPI.
    $loginStats = $pdo->query("SELECT
        COUNT(*) AS login_attempts,
        SUM(CASE WHEN action = 'login_success' THEN 1 ELSE 0 END) AS successful_logins,
        SUM(CASE WHEN action = 'login_failed' THEN 1 ELSE 0 END) AS failed_logins
        FROM activity_log
        WHERE action IN ('login_success', 'login_failed')")->fetch(PDO::FETCH_ASSOC);
    $userStats['login_attempts'] = (int)($loginStats['login_attempts'] ?? 0);
    $userStats['successful_logins'] = (int)($loginStats['successful_logins'] ?? 0);
    $userStats['failed_logins'] = (int)($loginStats['failed_logins'] ?? 0);

    // Only staff who actually have login credentials (username set) are
    // "system users" in the sense this screen manages - most rank-and-file
    // staff records have no username/password at all.
    $stmt = $pdo->query("SELECT
        s.svcNo, s.username, s.officialEmail, s.role, s.accStatus, s.dateCreated, s.lastLogin, s.passwordChangedAt, s.isFirstLogin,
        s.fName, s.mName, s.lName, s.rankId, s.branch_id, b.name AS branch_name
        FROM staff s
        LEFT JOIN branches b ON b.id = s.branch_id
        WHERE s.username IS NOT NULL
        ORDER BY s.dateCreated DESC");
    $userList = $stmt->fetchAll(PDO::FETCH_ASSOC);

    // Any account that has never completed a password change is always forced
    // through the first-login password-change flow. This also covers accounts
    // created by older ARMIS versions where isFirstLogin may not have been set.
    $pendingReset = $pdo->prepare("UPDATE staff SET isFirstLogin = 1 WHERE username IS NOT NULL AND username <> '' AND password IS NOT NULL AND password <> '' AND passwordChangedAt IS NULL AND (isFirstLogin IS NULL OR isFirstLogin <> 1)");
    $pendingReset->execute();
    if ($pendingReset->rowCount() > 0) {
        foreach ($userList as &$pendingUser) {
            if (empty($pendingUser['passwordChangedAt'])) {
                $pendingUser['isFirstLogin'] = 1;
            }
        }
        unset($pendingUser);
    }
} catch (Exception $e) {
    error_log("User data fetch error: " . $e->getMessage());
    $message = "Could not load staff/user data: " . $e->getMessage();
    $messageType = "danger";
}

include dirname(__DIR__) . '/shared/header.php';
include dirname(__DIR__) . '/shared/sidebar.php';
?>

<!-- Main Content -->
<div class="content-wrapper with-sidebar">
    <div class="container-fluid">
        <div class="main-content">
            <div class="row mb-4">
                <div class="col-12">
                    <div class="d-flex justify-content-between align-items-center gap-3 flex-wrap">
                        <div>
                            <h1 class="admin-section-title">
                                <i class="fas fa-users text-primary"></i> User & Account Management
                            </h1>
                            <p class="text-muted mb-0">Create login credentials for active personnel, then assign roles and branches to users who need administrative access.</p>
                        </div>
                        <div class="d-flex gap-2 flex-wrap">
                            <form method="POST">
                                <input type="hidden" name="action" value="diagnose_account_creation">
                                <input type="hidden" name="csrf_token" value="<?= htmlspecialchars($csrfToken) ?>">
                                <button type="submit" class="btn btn-outline-primary">
                                    <i class="fas fa-stethoscope me-1"></i> Test Account Creation
                                </button>
                            </form>
                            <form method="POST" onsubmit="return confirmBulkCreate();">
                                <input type="hidden" name="action" value="create_active_users">
                                <input type="hidden" name="csrf_token" value="<?= htmlspecialchars($csrfToken) ?>">
                                <button type="submit" class="btn btn-success btn-lg">
                                    <i class="fas fa-user-plus me-1"></i> Create Users for Active Personnel
                                </button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>

            <?php if ($message): ?>
            <div class="alert alert-<?= htmlspecialchars($messageType) ?> alert-dismissible fade show" role="alert">
                <?= htmlspecialchars($message) ?>
                <button type="button" class="btn-close" data-bs-dismiss="modal"></button>
            </div>
            <?php endif; ?>

            <?php if (!empty($_SESSION['last_reset_credentials'])): $resetCred = $_SESSION['last_reset_credentials']; unset($_SESSION['last_reset_credentials']); ?>
            <div class="alert alert-success shadow-sm border-0" role="alert">
                <div class="d-flex align-items-start gap-3">
                    <i class="fas fa-shield-alt fa-lg mt-1"></i>
                    <div class="flex-grow-1">
                        <h6 class="alert-heading mb-1">Password reset completed</h6>
                        <p class="mb-2">The temporary credential below is displayed once. The account is now marked <strong>Reset Required</strong> and the user must choose a new password at next login.</p>
                        <div class="row g-2 small">
                            <div class="col-md-4"><strong>Svc No:</strong> <?= htmlspecialchars($resetCred['svcNo']) ?></div>
                            <div class="col-md-4"><strong>Username:</strong> <?= htmlspecialchars($resetCred['username']) ?></div>
                            <div class="col-md-4"><strong>Temporary Password:</strong> <code><?= htmlspecialchars($resetCred['password']) ?></code></div>
                        </div>
                        <button type="button" class="btn btn-sm btn-outline-dark mt-2" onclick="copyResetCredential(<?= json_encode($resetCred['password']) ?>, this)"><i class="fas fa-copy me-1"></i> Copy Temporary Password</button>
                    </div>
                    <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
                </div>
            </div>
            <?php endif; ?>

            <?php if (!empty($generatedCredentials)): ?>
            <div class="alert alert-warning">
                <h5 class="alert-heading"><i class="fas fa-shield-alt me-1"></i> Newly Generated Temporary Credentials</h5>
                <p class="mb-2">These passwords are shown only because they were just generated. Save/transfer them securely. ARMIS stores only password hashes; the plaintext passwords cannot be recovered later. Every account is marked <strong>first login required</strong>.</p>
                <form method="POST" class="mb-3" onsubmit="return confirm('Export the newly generated credentials as a one-time CSV? The plaintext credentials will be removed from the server session after export.');">
                    <input type="hidden" name="action" value="export_credentials">
                    <input type="hidden" name="csrf_token" value="<?= htmlspecialchars($csrfToken) ?>">
                    <button type="submit" class="btn btn-dark"><i class="fas fa-file-csv me-1"></i> Export Newly Generated Credentials (One-Time)</button>
                </form>
                <div class="table-responsive bg-white rounded">
                    <table class="table table-sm table-bordered mb-0">
                        <thead class="table-dark"><tr><th>Svc No</th><th>Staff</th><th>Username</th><th>Temporary Password</th></tr></thead>
                        <tbody>
                        <?php foreach ($generatedCredentials as $cred): ?>
                            <tr><td><?= htmlspecialchars($cred['svcNo']) ?></td><td><?= htmlspecialchars($cred['name']) ?></td><td><code><?= htmlspecialchars($cred['username']) ?></code></td><td><code><?= htmlspecialchars($cred['password']) ?></code></td></tr>
                        <?php endforeach; ?>
                        </tbody>
                    </table>
                </div>
            </div>
            <?php endif; ?>

            <div class="row g-4 mb-5">
                <div class="col-xl-3 col-lg-6">
                    <div class="card bg-primary text-white h-100">
                        <div class="card-body">
                            <h6 class="card-title text-white-75"><i class="fas fa-right-to-bracket me-1"></i>Login Attempts</h6>
                            <h2 class="display-6 text-white"><?= number_format((int)($userStats['login_attempts'] ?? 0)) ?></h2>
                            <small class="text-white-75">
                                <?= number_format((int)($userStats['successful_logins'] ?? 0)) ?> successful ·
                                <?= number_format((int)($userStats['failed_logins'] ?? 0)) ?> failed
                            </small>
                        </div>
                    </div>
                </div>
                <div class="col-xl-3 col-lg-6">
                    <div class="card bg-success text-white h-100">
                        <div class="card-body">
                            <h6 class="card-title text-white-75">Active</h6>
                            <h2 class="display-6 text-white"><?= (int)($userStats['active_users'] ?? 0) ?></h2>
                        </div>
                    </div>
                </div>
                <div class="col-xl-3 col-lg-6">
                    <div class="card bg-secondary text-white h-100">
                        <div class="card-body">
                            <h6 class="card-title text-white-75">Active Without Accounts</h6>
                            <h2 class="display-6 text-white"><?= (int)($userStats['active_without_accounts'] ?? 0) ?></h2>
                            <small class="text-white-75">of <?= (int)($userStats['active_personnel'] ?? 0) ?> active personnel</small>
                        </div>
                    </div>
                </div>
                <div class="col-xl-3 col-lg-6">
                    <div class="card bg-danger text-white h-100">
                        <div class="card-body">
                            <h6 class="card-title text-white-75">Password Reset Required</h6>
                            <h2 class="display-6 text-white"><?= (int)($userStats['password_reset_pending'] ?? 0) ?></h2>
                            <small class="text-white-75">Never completed a password change</small>
                        </div>
                    </div>
                </div>
                <div class="col-xl-3 col-lg-6">
                    <div class="card bg-warning text-white h-100">
                        <div class="card-body">
                            <h6 class="card-title text-white-75">Privileged Roles</h6>
                            <h2 class="display-6 text-white"><?= (int)($userStats['privileged_users'] ?? 0) ?></h2>
                            <small class="text-white-75">Not the default 'user' role</small>
                        </div>
                    </div>
                </div>
                <div class="col-xl-3 col-lg-6">
                    <div class="card bg-info text-white h-100">
                        <div class="card-body">
                            <h6 class="card-title text-white-75">New This Month</h6>
                            <h2 class="display-6 text-white"><?= (int)($userStats['new_users_month'] ?? 0) ?></h2>
                        </div>
                    </div>
                </div>
            </div>

            <div class="card">
                <div class="card-header">
                    <h5 class="card-title mb-0"><i class="fas fa-list"></i> Accounts</h5>
                </div>
                <div class="card-body">
                    <div class="row g-2 mb-3 align-items-center">
                        <div class="col-lg-8">
                            <div class="input-group">
                                <span class="input-group-text"><i class="fas fa-search"></i></span>
                                <input type="search" class="form-control" id="userSearch" placeholder="Search service number, username, name, email, role, branch or status..." autocomplete="off">
                                <button type="button" class="btn btn-outline-secondary" id="clearUserSearch">Clear</button>
                            </div>
                        </div>
                        <div class="col-lg-4 text-lg-end">
                            <span class="badge bg-light text-dark border fs-6" id="userSearchCount"></span>
                        </div>
                    </div>
                    <div class="table-responsive">
                        <table class="table table-striped table-hover align-middle" id="usersTable">
                            <thead class="table-dark">
                                <tr>
                                    <th>Svc No</th>
                                    <th>Account</th>
                                    <th>Staff</th>
                                    <th>Role</th>
                                    <th>Branch</th>
                                    <th>Status</th>
                                    <th>Last Login</th>
                                    <th>Actions</th>
                                </tr>
                            </thead>
                            <tbody>
                                <?php foreach ($userList as $u): ?>
                                <tr class="user-row" data-search="<?= htmlspecialchars(strtolower(implode(' ', [
                                    $u['svcNo'] ?? '', $u['username'] ?? '', $u['officialEmail'] ?? '',
                                    $u['fName'] ?? '', $u['mName'] ?? '', $u['lName'] ?? '',
                                    $u['role'] ?? '', $u['branch_name'] ?? '', $u['accStatus'] ?? '', $u['rankId'] ?? ''
                                ])), ENT_QUOTES) ?>">
                                    <td><?= htmlspecialchars($u['svcNo']) ?></td>
                                    <td>
                                        <strong><?= htmlspecialchars($u['username']) ?></strong><br>
                                        <small class="text-muted"><?= htmlspecialchars($u['officialEmail'] ?? '') ?></small>
                                    </td>
                                    <td>
                                        <?= htmlspecialchars(trim(($u['lName'] ?? '') . ' ' . ($u['fName'] ?? '') . ' ' . ($u['mName'] ?? ''))) ?><br>
                                        <small class="text-muted"><?= htmlspecialchars($u['rankId'] ?? '') ?></small>
                                    </td>
                                    <td>
                                        <span class="badge bg-<?= ($u['role'] ?? 'user') === 'user' ? 'secondary' : 'primary' ?>">
                                            <?= htmlspecialchars($allRoles[$u['role']]['name'] ?? $u['role'] ?? 'user') ?>
                                        </span>
                                    </td>
                                    <td><?= htmlspecialchars($u['branch_name'] ?? '—') ?></td>
                                    <td>
                                        <span class="badge bg-<?= ($u['accStatus'] ?? '') === 'Active' ? 'success' : 'secondary' ?>">
                                            <?= htmlspecialchars($u['accStatus'] ?? 'Unknown') ?>
                                        </span>
                                        <?php if (empty($u['passwordChangedAt']) || (int)($u['isFirstLogin'] ?? 0) === 1): ?>
                                            <span class="badge bg-danger ms-1" title="This account must change its password"><i class="fas fa-lock"></i> Reset Required</span>
                                        <?php else: ?>
                                            <span class="badge bg-success ms-1" title="Password has been changed"><i class="fas fa-check"></i> Password Set</span>
                                        <?php endif; ?>
                                    </td>
                                    <td><small><?= $u['lastLogin'] ? date('M j, Y H:i', strtotime($u['lastLogin'])) : 'Never' ?></small></td>
                                    <td>
                                        <button class="btn btn-outline-primary btn-sm"
                                                onclick='openEdit(<?= json_encode($u) ?>)'
                                                data-bs-toggle="modal" data-bs-target="#editUserModal">
                                            <i class="fas fa-edit"></i>
                                        </button>
                                        <button class="btn btn-<?= (empty($u['passwordChangedAt']) || (int)($u['isFirstLogin'] ?? 0) === 1) ? 'danger' : 'outline-warning' ?> btn-sm" title="<?= (empty($u['passwordChangedAt']) || (int)($u['isFirstLogin'] ?? 0) === 1) ? 'Force password reset' : 'Reset password' ?>" onclick="resetPassword('<?= htmlspecialchars($u['svcNo'], ENT_QUOTES) ?>', <?= (empty($u['passwordChangedAt']) || (int)($u['isFirstLogin'] ?? 0) === 1) ? 'true' : 'false' ?>)">
                                            <i class="fas fa-key"></i> <?= (empty($u['passwordChangedAt']) || (int)($u['isFirstLogin'] ?? 0) === 1) ? 'Force Reset' : 'Reset' ?>
                                        </button>
                                    </td>
                                </tr>
                                <?php endforeach; ?>
                                <?php if (empty($userList)): ?>
                                <tr><td colspan="8" class="text-center text-muted py-4">No login accounts found.</td></tr>
                                <?php endif; ?>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="editUserModal" tabindex="-1">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Assign Role & Branch</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal"></button>
      </div>
      <form method="POST">
        <div class="modal-body">
          <input type="hidden" name="action" value="update_role_branch">
          <input type="hidden" name="csrf_token" value="<?= htmlspecialchars($csrfToken) ?>">
          <input type="hidden" name="svcNo" id="edit_svcNo">

          <div class="mb-3">
            <label class="form-label">Service Number</label>
            <input type="text" class="form-control" id="edit_svcNo_display" readonly>
          </div>

          <div class="mb-3">
            <label class="form-label">Role</label>
            <select class="form-select" name="new_role" id="edit_role">
              <?php foreach ($allRoles as $code => $r): ?>
                <option value="<?= htmlspecialchars($code) ?>"><?= htmlspecialchars($r['name']) ?></option>
              <?php endforeach; ?>
            </select>
          </div>

          <div class="mb-3">
            <label class="form-label">Branch</label>
            <select class="form-select" name="new_branch_id" id="edit_branch_id">
              <option value="">— None —</option>
              <?php foreach ($allBranches as $id => $b): ?>
                <option value="<?= (int)$id ?>"><?= htmlspecialchars($b['name']) ?><?= !empty($b['is_org_wide']) ? ' (Army-wide)' : '' ?></option>
              <?php endforeach; ?>
            </select>
            <small class="text-muted">Required for Chief Clerk, Staff Officer I/II/III and Director General. Not required for Adjutant General (org-wide by role) or System Administrator.</small>
          </div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
          <button type="submit" class="btn btn-primary">Save</button>
        </div>
      </form>
    </div>
  </div>
</div>

<div class="modal fade" id="resetPasswordModal" tabindex="-1" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content border-0 shadow">
      <div class="modal-header bg-light border-bottom">
        <div>
          <h5 class="modal-title mb-1"><i class="fas fa-key text-warning me-2"></i>Reset User Password</h5>
          <small class="text-muted">Administrative password reset</small>
        </div>
        <button type="button" class="btn-close" data-bs-dismiss="modal"></button>
      </div>
      <form method="POST" id="resetPasswordForm">
        <div class="modal-body">
          <input type="hidden" name="action" value="reset_password">
          <input type="hidden" name="csrf_token" value="<?= htmlspecialchars($csrfToken) ?>">
          <input type="hidden" name="svcNo" id="reset_svcNo">
          <div class="alert alert-warning d-flex gap-2 align-items-start">
            <i class="fas fa-exclamation-triangle mt-1"></i>
            <div><strong>Security action.</strong> The current password will be invalidated. ARMIS will generate a new temporary password and require the user to change it at next login.</div>
          </div>
          <div class="rounded border bg-light p-3 mb-3">
            <div class="d-flex justify-content-between mb-2"><span class="text-muted">Service Number</span><strong id="resetSvcDisplay">—</strong></div>
            <div class="d-flex justify-content-between"><span class="text-muted">Password history</span><span class="badge bg-success">Last 5 protected</span></div>
          </div>
          <div class="small text-muted"><i class="fas fa-info-circle me-1"></i> Previous passwords are stored only as secure hashes. ARMIS will reject a password that matches one of the user's recent passwords when the new permanent password is chosen.</div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
          <button type="submit" class="btn btn-warning" id="confirmResetBtn"><i class="fas fa-key me-1"></i> Generate Temporary Password</button>
        </div>
      </form>
    </div>
  </div>
</div>

<script>
function openEdit(u) {
    document.getElementById('edit_svcNo').value = u.svcNo;
    document.getElementById('edit_svcNo_display').value = u.svcNo;
    document.getElementById('edit_role').value = u.role || 'user';
    document.getElementById('edit_branch_id').value = u.branch_id || '';
}
function confirmBulkCreate() {
    const missing = <?= (int)($userStats['active_without_accounts'] ?? 0) ?>;
    return confirm('Create login accounts for ' + missing + ' active personnel who do not currently have complete credentials? Existing accounts will NOT be overwritten. Temporary passwords will be generated and shown once on this page.');
}
function resetPassword(svcNo, forced) {
    document.getElementById('reset_svcNo').value = svcNo;
    document.getElementById('resetSvcDisplay').textContent = svcNo;
    const btn = document.getElementById('confirmResetBtn');
    btn.innerHTML = '<i class="fas fa-key me-1"></i> ' + (forced ? 'Force Reset Password' : 'Generate Temporary Password');
    const modalEl = document.getElementById('resetPasswordModal');
    if (window.bootstrap && bootstrap.Modal) bootstrap.Modal.getOrCreateInstance(modalEl).show();
    else if (confirm('Reset the password for ' + svcNo + '?')) document.getElementById('resetPasswordForm').submit();
}
function copyResetCredential(value, button) {
    navigator.clipboard.writeText(value).then(function() {
        const original = button.innerHTML;
        button.innerHTML = '<i class="fas fa-check me-1"></i> Copied';
        setTimeout(() => button.innerHTML = original, 1800);
    });
}

(function initDynamicUserSearch() {
    const input = document.getElementById('userSearch');
    const clear = document.getElementById('clearUserSearch');
    const count = document.getElementById('userSearchCount');
    if (!input) return;
    const rows = Array.from(document.querySelectorAll('#usersTable tbody tr.user-row'));
    function applyFilter() {
        const query = input.value.trim().toLowerCase();
        let visible = 0;
        rows.forEach(row => {
            const match = !query || (row.dataset.search || '').includes(query);
            row.style.display = match ? '' : 'none';
            if (match) visible++;
        });
        if (count) count.textContent = visible + ' of ' + rows.length + ' accounts shown';
    }
    input.addEventListener('input', applyFilter);
    clear.addEventListener('click', function() { input.value = ''; input.focus(); applyFilter(); });
    applyFilter();
})();
</script>

<?php include dirname(__DIR__) . '/shared/footer.php'; ?>
